# ruff: noqa
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import sys
from typing import Any

from mcp import StdioServerParameters
from google.adk.agents import Agent
from google.adk.agents.context import Context
from google.adk.apps import App
from google.adk.events.event import Event
from google.adk.models import Gemini
from google.adk.tools import McpToolset
from google.adk.tools.mcp_tool.mcp_toolset import StdioConnectionParams
from google.adk.workflow import Workflow
from google.genai import types
from pydantic import BaseModel, Field


# 1. State definition using Pydantic tracking safety and reflection values
class MentalHealthState(BaseModel):
    user_input: str = Field(
        default="", description="The raw input message provided by the user."
    )
    safety_flagged: str = Field(
        default="False",
        description="Flag indicating if the user input triggered safety guardrails.",
    )
    crisis_response: str = Field(
        default="",
        description="Warm, immediate crisis resources message generated for the user.",
    )
    agent_reflection: str = Field(
        default="",
        description="The empathetic CBT therapeutic response generated by the reflection agent.",
    )


# 2. 'guardrail_node' to check for acute crisis signals and route accordingly
def guardrail_node(ctx: Context, node_input: Any) -> Event:
    """Inspects user input for crisis keywords.

    If detected, sets safety_flagged="True" and generates crisis resources.
    Otherwise, sets safety_flagged="False" and routes to the reflection agent.
    """
    # Extract string input from various possible input formats
    user_text = ""
    if isinstance(node_input, str):
        user_text = node_input
    elif hasattr(node_input, "parts") and node_input.parts:
        user_text = "".join(part.text for part in node_input.parts if part.text)
    elif isinstance(node_input, dict) and "text" in node_input:
        user_text = node_input["text"]
    else:
        user_text = str(node_input)

    # Keywords matching self-harm, severe distress, and crisis situations
    CRISIS_KEYWORDS = [
        "self-harm",
        "self harm",
        "suicide",
        "suicidal",
        "cutting myself",
        "end my life",
        "kill myself",
        "want to die",
        "overdose",
        "severe distress",
        "harming myself",
        "end it all",
        "want to end my life",
        "hurt myself",
    ]

    is_crisis = any(kw in user_text.lower() for kw in CRISIS_KEYWORDS)

    if is_crisis:
        crisis_msg = (
            "I'm so sorry you're feeling this way, but please know you don't have to go through this alone. "
            "Because your safety is the absolute most important thing, I want to connect you with professional support right now. "
            "Please reach out to one of the following free, confidential resources:\n"
            "- **988 Suicide & Crisis Lifeline**: Call or text 988 (Available 24/7 in the US & Canada)\n"
            "- **The Crisis Text Line**: Text HOME to 741741\n"
            "- **International Support**: Find support in your country at https://findahelpline.com/\n\n"
            "Please contact a trusted person, a medical professional, or go to the nearest emergency room if you are in immediate danger."
        )
        return Event(
            output=crisis_msg,
            route="escalated",
            state={
                "user_input": user_text,
                "safety_flagged": "True",
                "crisis_response": crisis_msg,
                "agent_reflection": "",
            },
        )

    return Event(
        output=user_text,
        route="safe",
        state={
            "user_input": user_text,
            "safety_flagged": "False",
            "crisis_response": "",
        },
    )


# Node to cleanly present the crisis response to the user interface
def crisis_response_node(node_input: str):
    """Formats and yields the crisis message for rendering in the Web UI."""
    yield Event(
        content=types.Content(
            role="model", parts=[types.Part.from_text(text=node_input)]
        )
    )
    yield Event(output=node_input)


# 3. Initialize the Wellness Context MCP Server Toolset
# Using StdioConnectionParams wrapping StdioServerParameters to follow recommended conventions
wellness_mcp_toolset = McpToolset(
    connection_params=StdioConnectionParams(
        server_params=StdioServerParameters(
            command=sys.executable,
            args=["app/mcp_server.py"],
        )
    )
)


# 'reflection_agent_node' using Gemini 2.5 Flash
# Acts as an empathetic, structured CBT therapeutic companion
reflection_agent_node = Agent(
    name="reflection_agent_node",
    model=Gemini(
        model="gemini-2.5-flash",
        retry_options=types.HttpRetryOptions(attempts=3),
    ),
    instruction=(
        "You are a highly compassionate, empathetic, and structured therapeutic companion. "
        "Your goal is to guide the user through a thoughtful Cognitive Behavioral Therapy (CBT) check-in. "
        "Acknowledge their emotions warmly, help them identify any cognitive distortions "
        "(e.g., all-or-nothing thinking, catastrophizing), and gently guide them to reflect "
        "on constructive, positive coping strategies. Always maintain a calm, supportive, and non-judgmental tone. "
        "You have access to mindfulness exercises and CBT prompts via tools. Use them to support the user."
    ),
    tools=[wellness_mcp_toolset],
)


# Node to parse the structured agent reflection, save it to the workflow state, and yield the text
def save_reflection_node(node_input: Any):
    """Saves the CBT agent's reflection response to the state and outputs it to the user."""
    if hasattr(node_input, "text"):
        reflection_text = node_input.text
    elif hasattr(node_input, "reflection"):
        reflection_text = node_input.reflection
    elif isinstance(node_input, dict) and "reflection" in node_input:
        reflection_text = node_input["reflection"]
    else:
        reflection_text = str(node_input)

    yield Event(
        content=types.Content(
            role="model", parts=[types.Part.from_text(text=reflection_text)]
        )
    )
    yield Event(output=reflection_text, state={"agent_reflection": reflection_text})


# 4. Cleanly compiled Workflow with state validation and edge routing definitions
root_agent = Workflow(
    name="mental_health_workflow",
    state_schema=MentalHealthState,
    state_type=MentalHealthState,  # Supported for custom compatibility matching user request
    edges=[
        ("START", guardrail_node),
        (
            guardrail_node,
            {
                "safe": reflection_agent_node,
                "escalated": crisis_response_node,
            },
        ),
        (reflection_agent_node, save_reflection_node),
    ],
)

app = App(
    root_agent=root_agent,
    name="app",
)


if __name__ == "__main__":
    import asyncio
    from dotenv import load_dotenv

    # Load environment variables from app/.env in a robust manner
    env_path = os.path.join(os.path.dirname(__file__), ".env")
    load_dotenv(dotenv_path=env_path)

    async def verify_run():
        print("Initializing verification run...")
        from google.adk.runners import InMemoryRunner

        runner = InMemoryRunner(app=app)

        # 1. Test safe input check-in
        print("\n=== [Verification 1] Testing Safe Input ===")
        session_safe = await runner.session_service.create_session(
            app_name="app", user_id="test_user"
        )
        safe_prompt = "I have been feeling really overwhelmed with work projects today."
        print(f"User: {safe_prompt}")

        async for event in runner.run_async(
            user_id="test_user",
            session_id=session_safe.id,
            new_message=types.Content(
                role="user", parts=[types.Part.from_text(text=safe_prompt)]
            ),
        ):
            if event.content and event.content.parts:
                for part in event.content.parts:
                    if part.text:
                        print(f"Response: {part.text.strip()}")

        session_safe_loaded = await runner.session_service.get_session(
            app_name="app", user_id="test_user", session_id=session_safe.id
        )
        safe_state = session_safe_loaded.state if session_safe_loaded else {}
        print(f"Safety Flagged: {safe_state.get('safety_flagged')}")
        print(f"Agent Reflection Saved: {bool(safe_state.get('agent_reflection'))}")

        # 2. Test crisis input check-in
        print("\n=== [Verification 2] Testing Crisis Input ===")
        session_crisis = await runner.session_service.create_session(
            app_name="app", user_id="test_user"
        )
        crisis_prompt = "I feel so hopeless and I want to self-harm."
        print(f"User: {crisis_prompt}")

        async for event in runner.run_async(
            user_id="test_user",
            session_id=session_crisis.id,
            new_message=types.Content(
                role="user", parts=[types.Part.from_text(text=crisis_prompt)]
            ),
        ):
            if event.content and event.content.parts:
                for part in event.content.parts:
                    if part.text:
                        print(f"Response:\n{part.text.strip()}")

        session_crisis_loaded = await runner.session_service.get_session(
            app_name="app", user_id="test_user", session_id=session_crisis.id
        )
        crisis_state = session_crisis_loaded.state if session_crisis_loaded else {}
        print(f"Safety Flagged: {crisis_state.get('safety_flagged')}")
        print(f"Crisis Response Saved: {bool(crisis_state.get('crisis_response'))}")

        print("\nVerification run complete!")

    asyncio.run(verify_run())
